-- MySQL Script generated by MySQL Workbench
-- 04/22/16 19:03:57
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema opnar
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema opnar
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `opnar` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `opnar` ;

-- -----------------------------------------------------
-- Table `opnar`.`tip_korisnika`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `opnar`.`tip_korisnika` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `naziv` VARCHAR(45) NULL COMMENT 'Komandant, zamenik, no, ng, referent',
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `opnar`.`korisnici`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `opnar`.`korisnici` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `ime` VARCHAR(15) NOT NULL COMMENT '',
  `prezime` VARCHAR(15) NOT NULL COMMENT '',
  `cin` VARCHAR(15) NULL COMMENT '',
  `created_at` DATETIME NULL DEFAULT CURRENT_TIMESTAMP COMMENT '',
  `tip_korisnika_id` INT NOT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  INDEX `fk_korisnici_tip_korisnika_idx` (`tip_korisnika_id` ASC)  COMMENT '',
  CONSTRAINT `fk_korisnici_tip_korisnika`
    FOREIGN KEY (`tip_korisnika_id`)
    REFERENCES `opnar`.`tip_korisnika` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `opnar`.`jedinica`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `opnar`.`jedinica` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `naziv` VARCHAR(45) NULL COMMENT '',
  `grb` VARCHAR(45) NULL COMMENT '',
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `opnar`.`vezbe`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `opnar`.`vezbe` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `naziv` VARCHAR(45) NULL COMMENT '',
  `datum_od` DATE NULL COMMENT '',
  `datum_do` DATE NULL COMMENT '',
  `zakljucenje` TINYINT(1) NULL COMMENT '',
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `opnar`.`nazivi_faze`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `opnar`.`nazivi_faze` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `nazivi` VARCHAR(45) NULL COMMENT '',
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `opnar`.`faze`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `opnar`.`faze` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `vezbe_id` INT NOT NULL COMMENT '',
  `nazivi_faze_id` INT NOT NULL COMMENT '',
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  INDEX `fk_faze_vezbe1_idx` (`vezbe_id` ASC)  COMMENT '',
  INDEX `fk_faze_nazivi_faze1_idx` (`nazivi_faze_id` ASC)  COMMENT '',
  CONSTRAINT `fk_faze_vezbe1`
    FOREIGN KEY (`vezbe_id`)
    REFERENCES `opnar`.`vezbe` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_faze_nazivi_faze1`
    FOREIGN KEY (`nazivi_faze_id`)
    REFERENCES `opnar`.`nazivi_faze` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `opnar`.`naslovi`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `opnar`.`naslovi` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `naslov` VARCHAR(45) NULL COMMENT '',
  `nosilac` VARCHAR(45) NULL COMMENT '',
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `opnar`.`tip_dokumenta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `opnar`.`tip_dokumenta` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `tip_dokumenta` VARCHAR(45) NULL COMMENT 'opnar, pripnar, naređere, zahtev...proracun vremena',
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '')
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
